name: Generate 3D Contribution Graph

on:
  workflow_dispatch:   # cho phép chạy thủ công
  schedule:
    - cron: "0 0 * * *"   # chạy mỗi ngày 0h

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          USERNAME: hoangprohigher   # 👈 quan trọng, thay bằng username của bạn

      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "generated 3d contribution graph"
          git push
